repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [--fix=lf]
  - repo: local
    hooks:
      # --------------------
      - id: black
        name: black
        entry: poetry run invoke black
        pass_filenames: false
        language: system
        types: [python]
      # --------------------
      - id: isort
        name: isort
        entry: poetry run invoke isort
        pass_filenames: false
        language: system
        types: [python]
      # --------------------
      - id: ruff
        name: ruff
        entry: poetry run invoke ruff
        pass_filenames: false
        language: system
        types: [python]
      # --------------------
      - id: pydocstyle
        name: pydocstyle
        entry: poetry run invoke pydocstyle
        pass_filenames: false
        language: system
        types: [python]
      # --------------------
      - id: pydoclint
        name: pydoclint
        entry: poetry run invoke pydoclint
        pass_filenames: false
        language: system
        types: [python]
      # --------------------
      - id: mypy
        name: mypy
        entry: poetry run invoke mypy
        pass_filenames: false
        language: system
        types: [python]
      # --------------------
      - id: coverage
        name: pytest / coverage
        entry: poetry run invoke coverage
        pass_filenames: false
        language: system
        types: [python]
